name: Gantt Chart Release tests workflow in Bundled OpenSearch Dashboards
on:
  pull_request:
    branches:
      - main
      - dev-*
jobs:
  tests:
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Gantt Chart
      test-command: yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/gantt-chart-dashboards/*'
      version: 1.3.0