name: Security Release tests workflow in Bundled OpenSearch Dashboards
on:
  pull_request:
    branches: [ '**' ]
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.filter.outputs.tests }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          tests:
            - 'cypress/**/security/**'

  tests:
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: Security
      test-command: env CYPRESS_NO_COMMAND_LOG=1 yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/security/*'
