name: Workspace Release tests workflow in Bundled OpenSearch Dashboards
on:
  pull_request:
    branches: ['**']

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.filter.outputs.tests }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            tests:
              - 'cypress/**/dashboards-workspace/**'
  tests-with-security:
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: dashboards workspace
      test-command: env CYPRESS_DASHBOARDS_WORKSPACE_ENABLED=true yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/dashboards-workspace/*'
      osd-serve-args: --workspace.enabled=true --savedObjects.permission.enabled: true
  tests-without-security:
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    uses: ./.github/workflows/release-e2e-workflow-template.yml
    with:
      test-name: dashboards workspace
      test-command: env CYPRESS_DASHBOARDS_WORKSPACE_ENABLED=true yarn cypress:run-with-security --browser chromium --spec 'cypress/integration/plugins/dashboards-workspace/*'
      osd-serve-args: --workspace.enabled=true --savedObjects.permission.enabled: true
      security-enabled: false